# ui/buttons.py
from pgzero.rect import Rect
from constants import WIDTH, HEIGHT

# === MENU LAYOUT CONSTANTS ===
BUTTON_X = 250
BUTTON_Y = 200
BUTTON_WIDTH = 300
STANDARD_BUTTON_HEIGHT = 50
START_BUTTON_HEIGHT = 60
VERTICAL_BUTTON_GAP = 10
VERTICAL_OFFSET = BUTTON_Y + START_BUTTON_HEIGHT + VERTICAL_BUTTON_GAP

# === MENU BUTTONS ===
start_button = Rect(BUTTON_X, BUTTON_Y, BUTTON_WIDTH, START_BUTTON_HEIGHT)

sound_button = Rect(
    BUTTON_X,
    VERTICAL_OFFSET,
    BUTTON_WIDTH // 2 - 5,
    STANDARD_BUTTON_HEIGHT
)

music_button = Rect(
    BUTTON_X + BUTTON_WIDTH // 2 + 5,
    VERTICAL_OFFSET,
    BUTTON_WIDTH // 2 - 5,
    STANDARD_BUTTON_HEIGHT
)

exit_button = Rect(
    BUTTON_X,
    VERTICAL_OFFSET + STANDARD_BUTTON_HEIGHT + VERTICAL_BUTTON_GAP,
    BUTTON_WIDTH,
    STANDARD_BUTTON_HEIGHT
)

# === IN-GAME MENU BUTTON ===
menu_button = Rect(WIDTH - 120, 10, 100, 40)
